# Generated by Django 3.1.6 on 2021-06-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
    ]
